@startuml

skinparam defaultFontName monospaced

'=======================================================================================================================
package render {
    '===================================================================================================================
    abstract class Renderable

    '===================================================================================================================
    abstract class Renderable2D extends Renderable {
        + {abstract} draw(render_2d::Renderer)
    }

    '===================================================================================================================
    abstract class Renderable3D extends Renderable {
        + {abstract} draw(render_3d::Renderer)
    }

    '===================================================================================================================
    abstract class RenderableObject {
        + {abstract} makeRenderRepresentation() -> Renderable
    }

    RenderableObject --> Renderable : "factory for"
}

'=======================================================================================================================
class SomeLogicObjectWhichShouldBeRendered implements render.RenderableObject {
    + makeRenderRepresentation() -> Renderable
}

'=======================================================================================================================
@enduml
