@startuml

skinparam defaultFontName monospaced

'=======================================================================================================================
package texture {
    '===================================================================================================================
    abstract class Texture
    abstract class TextureCreator

    '-------------------------------------------------------------------------------------------------------------------
    TextureCreator --> Texture
}

'=======================================================================================================================
package texture_storage {
    '===================================================================================================================
    class TextureId
    class TextureStorage

    '-------------------------------------------------------------------------------------------------------------------
    TextureStorage *-- TextureId
    TextureStorage *-- texture.Texture
}

'=======================================================================================================================
package content {
    '===================================================================================================================
    class Content

    '-------------------------------------------------------------------------------------------------------------------
    Content *-- Color : or
    Content *-- StaticTexture : or

    '-------------------------------------------------------------------------------------------------------------------
    StaticTexture *-- texture_storage.TextureId
}

'=======================================================================================================================
package renderer_context {
    '===================================================================================================================
    abstract class RendererContext
}

'=======================================================================================================================
package render_2d {
    '===================================================================================================================
    abstract class GeometryBatch
    abstract class Renderer

    '-------------------------------------------------------------------------------------------------------------------
    Renderer --> GeometryBatch
}

'=======================================================================================================================
package render_3d {
    '===================================================================================================================
    abstract class GeometryBatch
    abstract class Renderer

    '-------------------------------------------------------------------------------------------------------------------
    Renderer --> GeometryBatch
}

'=======================================================================================================================
package render {
    '===================================================================================================================
    abstract class Renderer

    '-------------------------------------------------------------------------------------------------------------------
    Renderer *-- renderer_context.RendererContext
    Renderer *-- texture_storage.TextureStorage : temporarily
    Renderer *-- texture.TextureCreator
    Renderer *-- render_2d.Renderer
    Renderer *-- render_3d.Renderer
}

'=======================================================================================================================
@enduml
