@startuml

skinparam defaultFontName monospaced

'=======================================================================================================================
package content {
    '===================================================================================================================
    class Color 

    '===================================================================================================================
    abstract class UpdatableContent {
        + {abstract} update()
    }

    abstract class Texture extends UpdatableContent 
    abstract class Image extends UpdatableContent
    abstract class Gif extends UpdatableContent
    abstract class Video extends UpdatableContent

    '===================================================================================================================
    class Content {
        Color
        uptr<Texture>
        // ...
    }

    note left : std::variant

    '-------------------------------------------------------------------------------------------------------------------
    Content *-- Color 
    Content *-- UpdatableContent  

    '===================================================================================================================
    class ContentStorage

    note top
        For media reusage 
        TODO: different renderers require 
          different ways of creating content. 
          How to incorporate Storage and 
          content creators? 
    end note
}

'=======================================================================================================================
package render_2d {
    '===================================================================================================================
    package geom_prim {
        class Line
        class Triangle
    }

    '-------------------------------------------------------------------------------------------------------------------
    geom_prim o-- content.Content

    '===================================================================================================================
    package text {
        class FontText
    }

    '-------------------------------------------------------------------------------------------------------------------
    text o-- content.Content
    
    '===================================================================================================================
    abstract class Renderer {
        + {abstract} draw(geom_prim::Line)
        + {abstract} draw(geom_prim::Triangle)
        + {abstract} draw(text::FontText)
        // ...
    }

    '-------------------------------------------------------------------------------------------------------------------
    Renderer --> geom_prim
    Renderer --> text
}

'=======================================================================================================================
package render_3d {
    '===================================================================================================================
    package geom_prim {
        class Line
        class Triangle
        class Tetrahedron
        class Brick
    }

    '-------------------------------------------------------------------------------------------------------------------
    geom_prim o-- content.Content
    
    '===================================================================================================================
    abstract class Renderer {
        + {abstract} draw(geom_prim::Line)
        // ...
        + {abstract} draw(geom_prim::Tetrahedron)
        // ...
    }

    '-------------------------------------------------------------------------------------------------------------------
    Renderer --> geom_prim
}

'=======================================================================================================================
package render {
    '===================================================================================================================
    abstract class Renderable

    '===================================================================================================================
    abstract class Renderable2D extends Renderable {
        + {abstract} draw(render_2d::Renderer)
    }

    '-------------------------------------------------------------------------------------------------------------------
    Renderable2D --> render_2d.Renderer

    '-------------------------------------------------------------------------------------------------------------------
    Renderable2D *-- render_2d.geom_prim
    Renderable2D *-- render_2d.text

    '===================================================================================================================
    abstract class Renderable3D extends Renderable {
        + {abstract} draw(render_3d::Renderer)
    }

    '-------------------------------------------------------------------------------------------------------------------
    Renderable3D --> render_3d.Renderer

    '-------------------------------------------------------------------------------------------------------------------
    Renderable3D *-- render_3d.geom_prim

    '===================================================================================================================
    abstract class RenderableObject

    '-------------------------------------------------------------------------------------------------------------------
    RenderableObject --> Renderable : "factory for"
}

'=======================================================================================================================
@enduml
