@startuml

skinparam defaultFontName monospaced

'=======================================================================================================================
package content {
    abstract class Content

    class Color implements Content
    class Texture implements Content
    class Image implements Content
    class Gif implements Content
    class Video implements Content

    class ContentMgr {
        + makeColor()
        + makeTexture()
        // ...
    }
}

'=======================================================================================================================
package render_2d {
    '===================================================================================================================
    package geom_prim {
        class Line
        class Triangle
    }

    '-------------------------------------------------------------------------------------------------------------------
    geom_prim o-- content

    '===================================================================================================================
    package text {
        class FontText
    }

    '-------------------------------------------------------------------------------------------------------------------
    text o-- content
    
    '===================================================================================================================
    abstract class Renderer {
        + {abstract} draw(geom_prim::Line)
        + {abstract} draw(geom_prim::Triangle)
        + {abstract} draw(text::FontText)
        // ...
    }

    '-------------------------------------------------------------------------------------------------------------------
    Renderer --> geom_prim
    Renderer --> text
}

'=======================================================================================================================
package render_3d {
    '===================================================================================================================
    package geom_prim {
        class Line
        class Triangle
        class Tetrahedron
        class Brick
    }

    '-------------------------------------------------------------------------------------------------------------------
    geom_prim o-- content
    
    '===================================================================================================================
    abstract class Renderer {
        + {abstract} draw(geom_prim::Line)
        // ...
        + {abstract} draw(geom_prim::Tetrahedron)
        // ...
    }

    '-------------------------------------------------------------------------------------------------------------------
    Renderer --> geom_prim
}

'=======================================================================================================================
package render {
    '===================================================================================================================
    abstract class Renderable

    '===================================================================================================================
    abstract class Renderable2D extends Renderable {
        + {abstract} draw(render_2d::Renderer)
    }

    '-------------------------------------------------------------------------------------------------------------------
    Renderable2D --> render_2d.Renderer

    '-------------------------------------------------------------------------------------------------------------------
    Renderable2D "1" *-- "0.." render_2d.geom_prim
    Renderable2D "1" *-- "0.." render_2d.text

    '===================================================================================================================
    abstract class Renderable3D extends Renderable {
        + {abstract} draw(render_3d::Renderer)
    }

    '-------------------------------------------------------------------------------------------------------------------
    Renderable3D --> render_3d.Renderer

    '-------------------------------------------------------------------------------------------------------------------
    Renderable3D "1" *-- "0.." render_3d.geom_prim

    '===================================================================================================================
    abstract class RenderableObject

    '-------------------------------------------------------------------------------------------------------------------
    RenderableObject --> Renderable : "factory for"
}



'=======================================================================================================================
@enduml
