@startuml

skinparam defaultFontName monospaced

'=======================================================================================================================
winsys --> Client : Provide abstract "WindowMgr"
winsys --> Client : Provide abstract "Window"

'-----------------------------------------------------------------------------------------------------------------------
====

'-----------------------------------------------------------------------------------------------------------------------
renderer_context --> Client : Provide abstract "RendererPreconfigOptions"
renderer_context --> Client : Provide abstract "RendererContextCreator"
renderer_context --> Client : Provide abstract "RendererContext"

'=======================================================================================================================
== Impl window and winmgr ==

'=======================================================================================================================
sdl_winsys <-- Client : Impl "SdlWindowMgr"
sdl_winsys <-- Client : Impl "SdlWindow"

'-----------------------------------------------------------------------------------------------------------------------
== SDL Renderer impl ==

'-----------------------------------------------------------------------------------------------------------------------
sdl_winsys <-- Client : Impl "SdlRenderContextCreator"

'-----------------------------------------------------------------------------------------------------------------------
sdl_renderer_context <-- Client : Impl "SdlRenderPreconfigOptions"
sdl_renderer_context <-- Client : Impl "SdlRenderContext"

'=======================================================================================================================
== OpenGL impl ==

'-----------------------------------------------------------------------------------------------------------------------
sdl_winsys <-- Client : Impl "OpenGlContextCreator"
sdl_winsys <-- Client : Impl "OpenGlContextOnSdl"

'-----------------------------------------------------------------------------------------------------------------------
opengl_context <-- Client : Impl "OpengGlPreconfigOptions"

'=======================================================================================================================
@enduml
