@startuml

skinparam defaultFontName monospaced

'=======================================================================================================================
package AppEvent_ {
    class AppEvent
}

'=======================================================================================================================
class EventQueue
class NativeEventListeners

'=======================================================================================================================
abstract class EventMgr {
    + pollEvents()
==
    + getNextEvent() : AppEvent
--
    + getEventQueue()
    + getNativeEventListeners()
==
    - {abstract} _fetchNativeEvents()
}

'------------------------------------------------------------------------------------------------------------------------
EventMgr *-- EventQueue
EventMgr *-- NativeEventListeners

'------------------------------------------------------------------------------------------------------------------------
EventMgr --> AppEvent : provides to client

'=======================================================================================================================
@enduml
