@startuml

skinparam defaultFontName monospaced

'=======================================================================================================================
package sdl_texture {
    '===================================================================================================================
    class SdlTexture {
        + getRawTexture() -> SdlTexture&
    }

    '===================================================================================================================
    class SdlTextureSampling

    '===================================================================================================================
    class SdlTexturingObjectsCreator  {
        + createTexture()
        + createTextureSampler()
    }

    '===================================================================================================================
    class SdlTexturingMgr  {
        + getTexturingObjectsCreator()
    --
        + setCurrentTextureSampler(TextureSampler*)
    }

    '-------------------------------------------------------------------------------------------------------------------
    SdlTexturingMgr *-- SdlTexturingObjectsCreator
    SdlTexturingMgr o-- SdlTextureSampling
}

'=======================================================================================================================
@enduml
