@startuml

skinparam defaultFontName monospaced

'=======================================================================================================================
package win_event {
    class WindowEvent
}

'=======================================================================================================================
package input_event {
    class KeyboardEvent
}

'=======================================================================================================================
package app_event {
    class AppEvent {
        one of
    ==
        None
        ...
    }
}

'------------------------------------------------------------------------------------------------------------------------
app_event.AppEvent *-- win_event.WindowEvent 
app_event.AppEvent *-- input_event.KeyboardEvent 

'=======================================================================================================================
@enduml
