#pragma once

#include <Common/String.h>

//======================================================================================================================
namespace keyboard {
    enum class KeyCode {
        Unknown,
        Exclamation,
        DoubleQuote,
        Hash,
        Dollar,
        Percent,
        Ampersand,
        Apostrophe,
        LeftRoundBracket,
        RightRoundBracket,
        Asterisk,
        Plus,
        Comma,
        Minus,
        Dot,
        Slash,
        Num0,
        Num1,
        Num2,
        Num3,
        Num4,
        Num5,
        Num6,
        Num7,
        Num8,
        Num9,
        Colon,
        Semicolon,
        LessThan,
        Equal,
        GreaterThan,
        Question,
        AtSign,
        A,
        B,
        C,
        D,
        E,
        F,
        G,
        H,
        I,
        J,
        K,
        L,
        M,
        N,
        O,
        P,
        Q,
        R,
        S,
        T,
        U,
        V,
        W,
        X,
        Y,
        Z,
        LeftSquareBracket,
        Backslash,
        RightSquareBracket,
        Caret,
        Underscore,
        Backtick,
        LeftCurlyBracket,
        VerticalBar,
        RightCurlyBracket,
        Tilde,
    };

    //------------------------------------------------------------------------------------------------------------------
    String str(KeyCode);
}
