#pragma once

#include <Common/String.h>

//======================================================================================================================
namespace keyboard {
    enum class KeyScancode {
        Unknown,
        A,
        B,
        C,
        D,
        E,
        F,
        G,
        H,
        I,
        J,
        K,
        L,
        M,
        N,
        O,
        P,
        Q,
        R,
        S,
        T,
        U,
        V,
        W,
        X,
        Y,
        Z,
        Num0,
        Num1,
        Num2,
        Num3,
        Num4,
        Num5,
        Num6,
        Num7,
        Num8,
        Num9,
        Enter,
        Escape,
        Backspace,
        Tab,
        Space,
        Apostrophe,
        Comma,
        Minus,
        Dot,
        Slash,
        Semicolon,
        Equal,
        LeftSquareBracket,
        Backslash,
        RightSquareBracket,
        Backtick,
        LCtrl,
        LShift,
        LAlt,
        LGui,
        RCtrl,
        RShift,
        RAlt,
        RGui,
    };

    //------------------------------------------------------------------------------------------------------------------
    String str(KeyScancode);
}
