@startuml

skinparam defaultFontName monospaced

'=======================================================================================================================
abstract class Framework {
    {abstract} + getAppEventMgr()
    {abstract} + getWindowMgr()
    {abstract} + getInputMgr()
    {abstract} + getAudioMgr()
    {abstract} + createRenderer()
}

'-----------------------------------------------------------------------------------------------------------------------
note top
    It is guaranteed that Framework is destroyed after all objects created by it.
    Use RAII guards for init/free of common parts of specific frameworks.
end note

'-----------------------------------------------------------------------------------------------------------------------
class SdlFramework implements Framework
class GlfwFramework implements Framework

'=======================================================================================================================
abstract class Application {
    + run()
--
    + {abstract} _init() : Framework
    + {abstract} _run()
--
    - _framework
}

'-----------------------------------------------------------------------------------------------------------------------
abstract class RenderableApplication implements Application {
    + {abstract} _iterate()
    + {abstract} _render()
    --
    + _run() 
    --
    + getClock() -> Clock
}

'-----------------------------------------------------------------------------------------------------------------------
Application *-- Framework

'=======================================================================================================================
@enduml
