@startuml

skinparam defaultFontName monospaced

'=======================================================================================================================
package event_sys {
    class EventMgr
}

package render {
    abstract class Renderer
}

package winsys {
    abstract class WindowMgr
}

'=======================================================================================================================
package framework {
    abstract class Framework

    Framework *-up- event_sys.EventMgr
    Framework *-up- render.Renderer
    Framework *-up- winsys.WindowMgr
}

'=======================================================================================================================
class SdlFramework implements framework.Framework
class GlfwFramework implements framework.Framework

'=======================================================================================================================
Client -right-> framework.Framework

@enduml
