@startuml

skinparam defaultFontName monospaced

'=======================================================================================================================
package WinEvent

'=======================================================================================================================
package KeyboardEvent

'=======================================================================================================================
package AppEvent

'------------------------------------------------------------------------------------------------------------------------
AppEvent --> WinEvent
AppEvent --> KeyboardEvent

'=======================================================================================================================
package EventInfo

'------------------------------------------------------------------------------------------------------------------------
EventInfo <-- WinEvent
EventInfo <-- KeyboardEvent

'=======================================================================================================================
package EventSys

'------------------------------------------------------------------------------------------------------------------------
EventSys --> AppEvent
EventSys <-- Client

'=======================================================================================================================
@enduml
